version: "3.8"

services:
  backend:
    build:
      context: ./api
    container_name: conectify-api
    networks:
      - traefik-net
    env_file:
      - ./api/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.atendai.tech`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=3051"

  frontend:
    build:
      context: ./app
    container_name: conectify-frontend
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`conectify.atendai.tech`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=8888"

networks:
  traefik-net:
    external: true
