name: Deploy com Docker e Traefik

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy via SSH com Docker
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "46.202.144.162"
          username: "root"
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/code/app-deploy/project-p4 || git clone https://github.com/italanleal/project-p4.git /root/code/app-deploy/project-p4
            cd /root/code/app-deploy/project-p4
            git pull origin main

            # Criar o .env na pasta api
            cat > ./api/.env <<EOF
            NEO4J_URI=${{ secrets.NEO4J_URI }}
            NEO4J_USERNAME=${{ secrets.NEO4J_USERNAME }}
            NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}
            NEO4J_DATABASE=${{ secrets.NEO4J_DATABASE }}
            EOF

            # Parar serviços que usam as portas, opcional
            fuser -k 3051/tcp || true
            fuser -k 8888/tcp || true

            # Subir containers com docker compose (rebuild)
            docker compose up -d --build
